### PR TITLE
#3037 Fix cucumber parallel remote driver 

### PR DESCRIPTION
**Pull request by GianniGiglio**
Fixes the remote driver issue and wrong eventBus for parallel execution

### CODE REVIEW

**Comment by wakaleo** [comment]
Thanks @GianniGiglio. @cliviu, could you review this please?

**Comment by cliviu** [comment]
@GianniGiglio , can you please try instead your change to replace line 75 of the original RemoteDriverProvider with `testOutcome = StepEventBus.getParallelEventBus().getBaseStepListener().getCurrentTestOutcome();` , see if it still works?

**Comment by GianniGiglio** [comment]
> testOutcome = StepEventBus.getParallelEventBus().getBaseStepListener().getCurrentTestOutcome()

Do you mean removing the if else statement?

**Comment by cliviu** [comment]
> > testOutcome = StepEventBus.getParallelEventBus().getBaseStepListener().getCurrentTestOutcome()
> 
> Do you mean removing the if else statement?
yes

**Comment by cliviu** [comment]
have you done the test? is still working?
what about the gradle improvements?

**Comment by GianniGiglio** [comment]
@cliviu  yeah tested it wrong. I'll get back to you in a sec

**Comment by GianniGiglio** [comment]
@cliviu 
tested: without and with junit5 parallelization and it works.
Regarding the other gradle changes they are already merged in main from a previous pr I made https://github.com/serenity-bdd/serenity-core/pull/3035.

My fork was just not updated

**Pull request merged**
