### PR TITLE
updated appium java client version

### PR DESCRIPTION
**Pull request by vikramvi**
Updated to latest Appium Java Client version

https://github.com/appium/java-client/tags

Please review

### CODE REVIEW

**Comment by wakaleo** [comment]
Thanks for your PR. Could you run "gradle clean test integrationTests" before committing? Version changes often lead to transitive dependency conflicts, where other dependencies also need to be updated.

**Comment by vikramvi** [comment]
Thanks for heads up, build indeed failed with below error

Any idea why might have went wrong, I did pretty small change and nothing related to commons-codec

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':serenity-core:compileClasspath'.
> A conflict was found between the following modules:
   - commons-codec:commons-codec:1.9
   - commons-codec:commons-codec:1.10
```

**Comment by wakaleo** [comment]
The latest Appium client must use commons-codec 1.10, whereas the Serenity code currently uses version 1.9. You need to update the commons-codec version as well.

**Comment by vikramvi** [comment]
Thanks, I got new error as below

Where do I need to put phanomjs browser in Mac OS, under system path is ok ?

```
net.thucydides.core.webdriver.WhenUsingWebElementFacadeExtender > classMethod FAILED
    java.lang.IllegalStateException: The path to the driver executable must be set by the phantomjs.binary.path capability/system property/PATH variable; for more information, see https://github.com/ariya/phantomjs/wiki. The latest version can be downloaded from http://phantomjs.org/download.html
        at com.google.common.base.Preconditions.checkState(Preconditions.java:750)
        at org.openqa.selenium.phantomjs.PhantomJSDriverService.findPhantomJS(PhantomJSDriverService.java:236)
        at org.openqa.selenium.phantomjs.PhantomJSDriverService.createDefaultService(PhantomJSDriverService.java:181)
        at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:105)
        at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:95)
        at net.thucydides.core.webdriver.WhenUsingWebElementFacadeExtender.$spock_initializeSharedFields(WhenUsingWebElementFacadeExtender.groovy:11)
```

**Comment by wakaleo** [comment]
Yes, you just need to put the phantoms binary on the path:

```
➜  serenity-core git:(master) which phantomjs
/usr/local/bin/phantomjs
```

**Comment by vikramvi** [comment]
one last query; to run tests on FF, do you take latest driver from https://github.com/mozilla/geckodriver/releases and put under system path ( /usr/local/bin) as well ?

**Comment by wakaleo** [comment]
Yes, that is correct.

**Comment by vikramvi** [comment]
There are some error related to FF ( 55.0.3 ) + geckodriver 0.18.0 I guess, but not related to this PR change.

Do you think we can merge this PR ?

```
> Task :serenity-junit:integrationTests

net.thucydides.junit.integration.WhenOpeningStaticDemoPageWithDifferentDrivers > the_user_opens_another_page FAILED
    org.openqa.selenium.SessionNotCreatedException: The following error occurred: Tried to run command without establishing a connection
    Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
    System info: host: 'Vikrams-MBP.fritz.box', ip: 'fe80:0:0:0:e5:e7ac:2a44:fb4c%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
    Driver info: org.openqa.selenium.remote.RemoteWebDriver
    Capabilities [{moz:profile=/var/folders/s5/s4vmm8jx3fqgt9s1tnn_0_v40000gn/T/rust_mozprofile.Oh4jJtWDBUKA, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=55.0.3, platformVersion=16.7.0, moz:processID=24306, browserName=firefox, javascriptEnabled=true, platformName=darwin}]
    Session ID: a6ca479c-c313-074c-9f1b-423f9ae919d9
    Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
    System info: host: 'Vikrams-MBP.fritz.box', ip: 'fe80:0:0:0:e5:e7ac:2a44:fb4c%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
    Driver info: driver.version: unknown

net.thucydides.junit.integration.WhenOpeningStaticDemoPageWithDifferentDrivers > classMethod FAILED
    org.openqa.selenium.SessionNotCreatedException: Tried to run command without establishing a connection
    Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
    System info: host: 'Vikrams-MBP.fritz.box', ip: 'fe80:0:0:0:e5:e7ac:2a44:fb4c%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
    Driver info: org.openqa.selenium.remote.RemoteWebDriver
    Capabilities [{moz:profile=/var/folders/s5/s4vmm8jx3fqgt9s1tnn_0_v40000gn/T/rust_mozprofile.Oh4jJtWDBUKA, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=55.0.3, platformVersion=16.7.0, moz:processID=24306, browserName=firefox, javascriptEnabled=true, platformName=darwin}]
    Session ID: a6ca479c-c313-074c-9f1b-423f9ae919d9
```

**Comment by vikramvi** [comment]
Thanks again for your quick support and review. Have a great day ahead

**Pull request merged**
