### PR TITLE
Try to fix issue #312 "Exception/assertion messages missing"

### PR DESCRIPTION
**Pull request by robertzett**
I've added some unit tests to issue #312 as well as the proposed change

### CODE REVIEW

**Comment by YamStranger** [comment]
Hello @robertzett 

Thanks for this pull request.

It seems for #321 but not for #312?

**Comment by robertzett** [comment]
Indeed it is for #321.
I've fixed my commit message.
Do you need a new pull request?

**Comment by YamStranger** [comment]
@robertzett 
it seems that updates of https://github.com/robertzett/serenity-core/commit/0a183ff32db818975f06fd046e76d7f7c84340b3 still refer to 312, please update commit message of it too.

No, you don't need new request 

Thanks )

**Comment by YamStranger** [comment]
Created pull request with these changes #328. Will close this pull request. 

@robertzett please review pull request #328 it should be identical to this, except messages and references to issue

Thanks for your contribution!!!!

**Pull request closed without merging**
