### PR TITLE
docs: Support Kobiton Cloud devices

### PR DESCRIPTION
**Pull request by khanhdodang**

### CODE REVIEW

**Comment by khanhdodang** [comment]
Hi, @wakaleo Could you please help me review my PR? Thanks.

**Comment by frankwmoyer** [comment]
@wakaleo, it appears the CI is down. When I click on *Details* it times out.

**Comment by wakaleo** [comment]
I will take a look tomorrow

**Comment by khanhdodang** [comment]
Yes, you are right. I follow other sample to run test on iOS app, but it just supports simulator. I wrote this sample to run test on real device.

**Pull request merged**
