### PR TITLE
Update Locatable to interactions package

### LINKED ISSUE #1012: Action moveToElement stop working in serenity after Selenium upgraded to 3.7.0
I have a method 
```
protected void moveToElement(WebElementFacade e){
         withAction().moveToElement(e).perform();
    }
```
in serenity 1.6.5 this method is working (there is a Selenium v3.5.3 ) fine but when I've updated seretiry to 1.7.0 (Selenium v.3.6.0) it stop working and throw an exception  
I did debug and find that exception is appeared class MouseAction in getActionLocation

```
public abstract class MouseAction extends BaseAction implements IsInteraction {
.........
    protected Coordinates getActionLocation() {
        return this.where == null ? null : this.where.getCoordinates();
    }
}
```
The stacktrace of exception
java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to org.openqa.selenium.internal.Locatable
	at net.serenitybdd.core.pages.WebElementFacadeImpl.getCoordinates(WebElementFacadeImpl.java:1109)
	at org.openqa.selenium.interactions.internal.MouseAction.getActionLocation(MouseAction.java:61)
	at org.openqa.selenium.interactions.MoveMouseAction.perform(MoveMouseAction.java:43)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:36)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:641)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:594)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:425)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:410)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:385)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:133)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at net.serenitybdd.junit.runners.SerenityStatement.evaluate(SerenityStatement.java:33)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:472)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:447)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:55)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:252)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitSt

java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to org.openqa.selenium.internal.Locatable
at com.framework.AjaxPageObject.moveToElement(AjaxPageObject.java:153)

Could you please take a look and fix.
Thanks
BR Alex

### PR DESCRIPTION
**Pull request by lega-land**
Update according to https://github.com/SeleniumHQ/selenium/commit/b37c27b4c62c4ba336a3a96b125f86ad0f15f04b

Fixes #1012

### CODE REVIEW

**Comment by wakaleo** [comment]
Thanks for your contribution.

**Comment by ThaKing** [comment]
**Serenity**: from 1.7.2 to 1.7.4
**Selenium**: 3.7.1
After Serenity 1.7.2 the exception appeared in **Action** class in **moveToElement** method

> [main] ERROR net.serenitybdd.core.Serenity - com.sun.proxy.$Proxy26 cannot be cast to org.openqa.selenium.internal.Locatable
> public Actions moveToElement(WebElement target)

**Comment by wakaleo** [comment]
@ThaKing Are you still seeing an issue?

**Comment by ThaKing** [comment]
Yes, it's appearing

**Comment by wakaleo** [comment]
Feel free to update the PR.

**Comment by ThaKing** [comment]
What do you mean `update the PR`?

**Comment by wakaleo** [comment]
If you have found an error, please feel free to propose a PR to fix it - it should just be a package name change as the Selenium APIs have changed.

**Comment by ThaKing** [comment]
Ok, thanks

**Comment by ThaKing** [comment]
We are sorry. We had `selenium-remote-driver` 3.5.2 version. Everything is OK

**Comment by wakaleo** [comment]
Thanks for the update, that particular Selenium API change seems to be causing hassles for quite a few people.

**Pull request merged**
