### PR TITLE
make WEBDRIVER_CHROME_BINARY work

### PR DESCRIPTION
**Pull request by SiKing**
Please let me know what I need to do to get this MR accepted.

### CODE REVIEW

**Comment by wakaleo** [comment]
Look's good, thanks.

**Comment by SiKing** [comment]
@wakaleo Do you have an ETA when this will hit the streets?

**Comment by wakaleo** [comment]
Probably this weekend.

**Comment by SiKing** [comment]
I just realized: https://github.com/serenity-bdd/serenity-documentation/blob/master/src/asciidoc/system-props.adoc should probably be updated as part of this MR. Is that done automagically?

**Pull request merged**
