### PR TITLE
removed failing test case from WhenDanaBrowsesTheWeb

### PR DESCRIPTION
**Pull request by vikramvi**
removed shouldSeeCorrectLegacyClientDetails test case as there is no ProfilePage.SOME_BUTTON
Please review

gradle clean test integrationTests

BUILD SUCCESSFUL in 12m 17s
75 actionable tasks: 75 executed

### CODE REVIEW

**Comment by vikramvi** [comment]
@wakaleo can you please share jenkins failure log ? Last time I checked jenkins job was gree, not sure what changed suddenly.

Also please review this small fix

**Comment by wakaleo** [comment]
Thanks for this Vikram, I actually did a fix at the same time on my side, so the latest version should work correctly for you.

**Comment by vikramvi** [comment]
@wakaleo this branch has all the changes from upstream master, I have rechecked this. Is there a way to re-run jenkins job again ?

**Comment by wakaleo** [comment]
There are some issues with the build server at the moment that I am investigating. But I won't be merging this change as such (the one that comments out the test), as I removed the offending button in the test on master (the test is still necessary).

**Comment by vikramvi** [comment]
I'm confused wrt last comment; without Button the test case will keep on failing. Is it ok to keep it that way ?

**Pull request closed without merging**
