### PR TITLE
Issue #532: Serenity/Screenplay does not permit a web application to be easily testable if it is presented in one or more iframes

### PR DESCRIPTION
**Pull request by nbarrett**
feat: added support for iframe switching within the TargetResolver.

### CODE REVIEW

**Comment by nbarrett** [comment]
Hi @wakaleo - I'm at a bit of loss to know how to resolve the broken build on this PR as the tests are not related to the modules I've made changes. Any advice recommended - I'd like to help/understand more!

**Comment by nbarrett** [comment]
Hi again @wakaleo - I've just rebased this PR and `./gradlew clean test` from `serenity-core/serenity-screenplay-webdriver` passes fine so still at a loss 😢

**Comment by wakaleo** [comment]
I am trying to refactor this into the code base, at the moment it impacts too many classes and would be hard to maintain.

**Comment by nbarrett** [comment]
This is replaced by #738.

**Pull request closed without merging**
