### PR TITLE
Functionality for creating fullpage screenshots

### PR DESCRIPTION
**Pull request by daniilmatafonov**
@wakaleo ,
I have done a pull request with the ability to create screenshots of the entire browser page. Could you please check it?

### CODE REVIEW

**Comment by daniilmatafonov** [comment]
@wakaleo, 
Could you please send me a log with an error ? Unfortunately, I can't get an access for jenkins ci machine to check log.

**Comment by daniilmatafonov** [comment]
@wakaleo,

I checked that you've been merged my PR. Thank you for your improvements of my changes. 
I wanted to clarify when you will be able to create a build?

**Comment by JagadeesanV** [comment]
@wakaleo @daniilmatafonov - I tried using the new feature (which is something I have been waiting for a long time) but I am running into the following issue inside the ShutterBug library.

In the Browser.java class  method BufferedImage takeScreenshotEntirePage() checks for the driver instance. For some reason my driver instance is coming back as a WebDriverFacade. 

Please let me know if you ran into this issue. 

Note - I am overriding the DriverSource and create my own custom driver.

**Comment by pnakhat** [comment]
Does anyone know how to use this property?

**Pull request merged**
