### PR TITLE
feat: #1928 - generate a machine-readable report file

### PR DESCRIPTION
**Pull request by trashytop**
#### Summary of this PR
This is a new feature to generate a machine-readable JSON report file.  This file contains the metrics currently displayed on the main report page.  Uses the ExtendedReport interface.

Key files for review:
* JsonSummaryReport.kt and JsonSummaryReporter.kt
* resources\templates\json-summary.ftl
* WhenGeneratingAJsonSummaryReport.kt and WhenConfiguringHighlightedFeatureTags.kt  (JUnit tests)

#### Intended effect
When configured, Serenity will create a serenity-summary.json file when it performs the aggregation task.

#### How should this be manually tested?
Add the dependency for the **serenity-machine-readable-reports** module and specify the **json-summary** report.  Similar to adding the dependency for the **serenity-emailer** module and specifying the **email** report.

#### Side effects
None,

#### Documentation
Suggest adding to https://serenity-bdd.github.io/theserenitybook/latest/extended-reports.html.  Please let me know how to do this!

#### Relevant tickets
#1928 

#### Screenshots (if appropriate)
N/A

### CODE REVIEW

**Comment by trashytop** [comment]
serenity-emailer and serenity-reports-configuration have almost (but not quite!) duplicate configuration classes, e.g. PathReportProperty.  I didn't want to introduce a dependency to serenity-emailer from serenity-machinereadable-reports so I've just copied the classes for now.

All three sets should be merged at some point but I didn't want to complicate this PR any further.

**Comment by trashytop** [comment]
I've also copied the serenity-emailer resource test-outcomes for now - a future PR should have a single copy in a common area.

**Comment by trashytop** [comment]
I've done my best when naming the properties in the JSON file, but still have some worries:

* success v passing
* error v broken
* tagCoverages - yuck!

**Comment by trashytop** [comment]
I didn't manage to get all of the JUnit tests from the other modules to pass successfully on my Windows 10 machine.

Most of the failures seems to be to do with strange file prefixes.  For example, I could fix the serenity-emailer tests by:

val TEST_OUTCOMES_WITH_MULTIPLE_RESULTS = ClassLoader.getSystemResource("test_outcomes/with_different_results").path

->

val TEST_OUTCOMES_WITH_MULTIPLE_RESULTS = File(ClassLoader.getSystemResource("test_outcomes/with_different_results").file).toPath()
WhenGeneratingAnEmailableReport

**Comment by trashytop** [comment]
serenity-machine-readable-reports is based on serenity-emailer.  Here's a summary of the main changes:

* Uses FreeMarker template (see json-summary.ftl)
* JUnit tests modified to use Gson to verify JSON properties correctly populated
* tagResults added to fields hashmap in JsonSummaryReport.templateFields

**Comment by trashytop** [comment]
I've tried to investigate the failed check mentioned above, but can't access 

http://54.77.148.38:8080/job/serenity-bdd/job/serenity-core/job/PR-1929/1/display/redirect

**Comment by trashytop** [comment]
Example machine-readable JSON report file:

[serenity-summary.zip](https://github.com/serenity-bdd/serenity-core/files/4118025/serenity-summary.zip)

**Comment by globalworming** [comment]
image
the changed files look alright at first glance.. i don't have the experience with cucumber to say if tags are implemented correctly

**Pull request merged**
