### PR TITLE
Fix #3141 #2920 - Make Junit recognise and report assertion failures

### LINKED ISSUE #3141: SerenityJUnit5Extension does not fail tests annotated with @DisplayName or @DisplayNameGeneration
If your test method has a `@DisplayName()` annotation, then Serenity will NOT mark the test as failed in case of an assertion error thrown by a @Step-annotated method in a @Steps class.

The reason is due to the discrepancy between these two spots:
- `SerenityJUnit5Extension#afterEach()` method, which [checks only the actual Java Method name](https://github.com/serenity-bdd/serenity-core/blob/main/serenity-junit5/src/main/java/net/serenitybdd/junit5/SerenityJUnit5Extension.java#L67)
- SerenityTestExecutionListener#testStarted, which [uses the @DisplayName or @DisplayNameGeneration annotations, if available, to generate the test method name](https://github.com/serenity-bdd/serenity-core/blob/main/serenity-junit5/src/main/java/net/serenitybdd/junit5/SerenityTestExecutionListener.java#L423)

### Sample fix

I have verified that I can fix this by using the following replacement for the `SerenityJUnit5Extension`:

```
@Log4j2
public class TestFailingSerenityJUnit5Extension extends SerenityJUnit5Extension {

  @Override
  public void afterEach(final ExtensionContext context) {
    if (!StepEventBus.getEventBus().isBaseStepListenerRegistered()) {
      log.warn("NO BASE STEP LISTENER FOUND IN THREAD " + Thread.currentThread());
    }
    final TestOutcome outcome = StepEventBus.getEventBus().getBaseStepListener().getCurrentTestOutcome();
    final String methodName = outcome.getQualifiedMethodName();
    context.getTestMethod().ifPresent(
        method -> {
          final String actualMethodName = JUnit5TestMethodAnnotations.forTest(method)
              .getDisplayName()
              .orElse(method.getName());

          // Make sure it's the right test - not sure when this gets called in parallel testing.
          if (actualMethodName.equals(methodName)) {
            // Failing test
            if (outcome.getTestFailureCause() != null) {
              throw outcome.getTestFailureCause().asRuntimeException();
            } else if (outcome.isPending()) {
              throw new PendingTestException(context.getDisplayName());
            } else if (outcome.isSkipped()) {
              throw new SkippedTestException(context.getDisplayName());
            }
          }
        }
    );
  }

}
```

(Note that this has only been tested with `@DisplayName`, not with `@DisplayNameGeneration` and also not with any qualifiers)

### Sample Setup
```
@ExtendWith(SerenityJUnit5Extension.class)
class TestIT {
   @Steps
   StepClass stepClass
   @Test
   @Displayname("blah")
   void test() { 
      stepClass.validateStuff()
  }
}
class StepClass {
   @Step
   validateStuff() {
     throw new AssertionError("...error...")
   }
}
```

### PR DESCRIPTION
**Pull request by bachhavdipak**
Make Junit recognise and report assertion failures

### CODE REVIEW

**Comment by bachhavdipak** [comment]
@wakaleo : Is it because of my changes ? if so then can you please let me know which test is failing ?

**Comment by wakaleo** [comment]
Yes, your changes cause a large number of unit tests to break:
```
[ERROR] Failures: 
[ERROR]   WhenRecordingStepExecutionResults.a_failing_step_should_record_the_failure:649 Step failed
[ERROR]   WhenRecordingStepExecutionResults.a_failing_step_should_record_the_failure_cause:792 Step failed
[ERROR]   WhenRecordingStepExecutionResults.a_failing_step_should_record_the_failure_details_with_the_step:835 Step failed
[ERROR]   WhenRecordingStepExecutionResults.after_a_failing_step_subsequent_errors_should_be_ignored:758 Step failed
[ERROR]   WhenRecordingStepExecutionResults.after_a_failing_step_subsequent_unannotated_errors_should_be_ignored:775 Step failed
[ERROR]   WhenRecordingStepExecutionResults.should_call_object_methods_normally_after_test_failures:739 Step failed
[ERROR]   WhenRecordingStepExecutionResults.should_return_failing_test_exception:1206 Step failed
[ERROR]   WhenRecordingStepExecutionResults.steps_should_be_skipped_after_a_failure:1104 Step failed
[ERROR]   WhenRecordingStepExecutionResults.steps_should_be_skipped_after_a_failure_in_a_nested_step:1123 Step failed
[ERROR]   WhenRecordingStepExecutionResults.steps_with_failing_nested_steps_should_record_the_step_failure:1188 Step failed
[ERROR]   WhenRecordingStepExecutionResultsForNonWebTests.a_failing_step_should_record_the_failure_cause_for_non_webtest_steps:192 Step failed
[ERROR]   WhenRecordingStepExecutionResultsForNonWebTests.a_failing_step_should_record_the_failure_for_non_webtest_steps:176 Step failed
[ERROR]   WhenRunningNonWebStepsThroughAScenarioProxy.the_proxy_should_skip_tests_after_a_failure:236 Oh bother
[ERROR]   WhenRunningStepsThroughAScenarioProxy.the_proxy_should_notify_listeners_when_a_failure_occurs_in_a_group:592 Oh bother!
[ERROR]   WhenRunningStepsThroughAScenarioProxy.the_proxy_should_notify_listeners_when_a_method_that_is_not_a_step_fails:654 Oops!
[ERROR]   WhenRunningStepsThroughAScenarioProxy.the_proxy_should_notify_listeners_when_a_step_fails:566 Oops!
[ERROR]   WhenRunningStepsThroughAScenarioProxy.the_proxy_should_notify_listeners_with_a_description_and_a_cause_when_a_failure_occurs_in_a_group:601 Oh bother!
[ERROR]   WhenRunningStepsThroughAScenarioProxy.the_proxy_should_notify_listeners_with_a_description_and_a_cause_when_a_non_step_fails:663 Oops!
[ERROR]   WhenRunningStepsThroughAScenarioProxy.the_proxy_should_notify_listeners_with_a_description_and_a_cause_when_a_step_fails:575 Oops!
[ERROR]   WhenRunningStepsThroughAScenarioProxy.the_proxy_should_skip_tests_after_a_failure:520 Oops!
[ERROR]   WhenRunningStepsThroughAScenarioProxy.the_proxy_skipped_nested_step_methods_after_failure_if_nested_calls_are_disabled:731 Deliberate failure
[ERROR]   WhenUsingTheStepEventBus.a_step_can_return_a_step_object_if_a_failure_occurs:629 
Expected: is <false>
     but: was <true>
[ERROR]   WhenUsingTheStepEventBus.should_not_use_the_browser:585 
Expected: is <false>
     but: was <true>
[ERROR]   WhenUsingTheStepEventBus.should_record_step_failures:382 
Expected: is <false>
     but: was <true>
[ERROR]   WhenUsingTheStepEventBus.should_skip_nested_steps_after_a_step_failure:560 
Expected: is <false>
     but: was <true>
[ERROR]   WhenUsingTheStepEventBus.should_skip_steps_after_a_step_failure:511 
Expected: is <false>
     but: was <true>
[ERROR] Errors: 
[ERROR]   WhenRunningStepsThroughAScenarioProxy.the_proxy_should_notify_listeners_when_a_web_method_that_is_not_a_step_fails:674 » SerenityManaged The following error occurred: Oops!
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.4.1', java.version: '20.0.1'
Driver info: driver.version: unknown
[ERROR]   WhenRunningStepsThroughAScenarioProxy.the_proxy_should_notify_listeners_when_a_web_step_fails:617 » SerenityManaged The following error occurred: Oops!
[ERROR]   WhenRunningStepsThroughAScenarioProxy.the_proxy_should_notify_listeners_when_a_web_step_fails_to_find_an_element:627 » NoSuchElement Could not find element
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.4.1', java.version: '20.0.1'
Driver info: driver.version: unknown
[ERROR]   WhenRunningStepsThroughAScenarioProxy.the_proxy_should_notify_listeners_with_a_description_and_a_cause_when_a_web_non_step_fails:683 » SerenityManaged The following error occurred: Oops!
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.4.1', java.version: '20.0.1'
Driver info: driver.version: unknown
[ERROR]   WhenRunningStepsThroughAScenarioProxy.the_proxy_should_notify_listeners_with_a_description_and_a_cause_when_a_web_step_fails:638 » SerenityManaged The following error occurred: Oops!
[ERROR]   WhenRunningStepsThroughAScenarioProxy.the_proxy_skipped_nested_step_methods_after_errors_if_nested_calls_are_disabled:745 » NullPointer Deliberate failure
[ERROR]   WhenRunningStepsThroughAScenarioProxy.the_proxy_skipped_nested_step_methods_after_ignored_steps_if_nested_calls_are_disabled:759 » NullPointer Deliberate failure
[ERROR]   WhenStepFailedInStepsWithTestData.should_skip_step_after_first_failed:121 » InvocationTarget
[ERROR]   WhenStepFailedInStepsWithTestData.should_skip_step_after_first_failed_in_one_iteration:107 » InvocationTarget
[INFO] 
[ERROR] Tests run: 1729, Failures: 26, Errors: 9, Skipped: 8
```

You can run mvn verify to make sure all the tests pass.

**Comment by GerMoranOverstock** [comment]
Should #3141 & #2920 be reopened given the change was reverted

**Comment by wakaleo** [comment]
#2920 and #3141 seems to work correctly with 3.9.7.

**Pull request merged**
