### PR TITLE
fixing display issues when using <> or \" characters in scenario outline titles / data table values

### PR DESCRIPTION
**Pull request by eitzenbe**

### CODE REVIEW

**Comment by eitzenbe** [comment]
@wakaleo Now its against your repo ;)

**Comment by wakaleo** [comment]
Are you sure? Still seeing the errors: 
image

**Comment by wakaleo** [comment]
Backing this out to redo.

**Comment by wakaleo** [comment]
Could you raise a fresh PR with these changes?

**Comment by eitzenbe** [comment]
Check but it will be Sunday... On to some mountain hiking

**Pull request merged**
