### PR TITLE
Use individual options over DesiredCapabilities

### LINKED ISSUE #1266: Use new FirefoxOptions() over DesiredCapabilities.firefox()
Running Serenity using firefox leads to the following spammed message in the logs:
```
INFORMATION: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
Jun 01, 2018 12:03:29 PM org.openqa.selenium.remote.DesiredCapabilities firefox
```
There are some variations where exactly the "deprecated" method is being called, but the message should be pretty clear: No more usage anywhere, use the newer, better alternative.
While this isn't breaking anything this error message is pretty annoying and makes actual error messages harder to find.

Fixing this should be pretty easy (and the same problem should be present for all the other browsers as well see [the DesiredCapabilities class](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/DesiredCapabilities.java) for more information), because it's really just an alternative API that returns an object of more or less the same type. (Same superclass).

I'd appreciate if this could get fixed soon.

### PR DESCRIPTION
**Pull request by RoiEXLab**
Fixes #1266 

As a side note: You really want to get rid of those circular dependencies in gradle, eclipse won't compile this code by default, and the kotlin compiler produces a stackoverflow for me 🤔

### CODE REVIEW

**Comment by wakaleo** [comment]
Thanks for your contribution!

**Comment by wakaleo** [comment]
Rolling this back as it doesn't work (causes null pointer exceptions in the event bus). Did you run the tests locally?

**Comment by RoiEXLab** [comment]
I did run the unit tests, but they were failing for me already before I made any changes.
I figured I was missing some sort of external dependency, so I tweaked my changes until I got the exact same test failures as before.
Apologies if that changed behaviour,I was actually expecting a continuous integration build for pull requests.

**Comment by wakaleo** [comment]
It was actually an environmental issue on my side, but I’ve made the error messages more friendly so all good now

**Comment by wakaleo** [comment]
This may have caused a regression (#1427).

**Comment by wakaleo** [comment]
I'm rolling. back this change because it breaks the switches in chrome and prevents things like headless browsing from working correctly.

**Pull request merged**
