### PR TITLE
Named page to support parameterized URL

### PR DESCRIPTION
**Pull request by arustamov**
1. EnvironmentSpecificConfiguration VARIABLE_EXPRRESSION_PATTERN updated to support parameterized named page urls like #{webdriver.base.url}/{1}
2. PageUrls named page parameters substitution to happen AFTER page name property resolution

### CODE REVIEW

**Comment by wakaleo** [comment]
Looks good. Could you include some unit tests to illustrate how it works?

**Comment by arustamov** [comment]
Recently I've migrated to environment specific setup according to https://johnfergusonsmart.com/environment-specific-configuration-in-serenity-bdd
and faced with the issue of not being able to resolve named page URLs like #{webdriver.base.url}/{1}

So here EnvironmentSpecificConfiguration pattern updated to correctly process the URL
and PageUrls updated to resolve page name property BEFORE parameters resolution and not AFTER as it is now

**Comment by wakaleo** [comment]
Yes, this explains the context well. Could you add a couple of unit tests to illustrate how the code works and protect against future regressions?

**Comment by arustamov** [comment]
@wakaleo 
Please advise on this since currently running `gradle test` I can see the following status:
1394tests | 6failures | 6ignored | 2m15.40sduration
So I need a reference to maybe similar unit tests to take a look to implement those you've asked

**Comment by wakaleo** [comment]
Have a look at `WhenDefiningPageUrls`.

There shouldn't be any failures in the unit tests, but the build will expect gheckdriver, chromedriver and phantomjs to be on the path for the integration tests. There may be some path-specific tests - which ones are failing?

**Comment by arustamov** [comment]
Here is the list:

WhenLoadingNarrativeDescriptionFromADirectory. Should be able to derive the narrative type from the directory level
WhenLoadingNarrativeDescriptionFromADirectory. Should use the lowest requirement type for deeply nested requirements
WhenLoadingRequirementOutcomesFromTheFileSystem. Should be able to customize the requirements levels
WhenLoadingRequirementOutcomesFromTheFileSystem. default nested requirement types can be overriden using an environment variable
WhenLoadingRequirementOutcomesFromTheFileSystem. nested capability types are set by convention if no narrative.txt files are present
WhenLoadingRequirementsFromAPackageStructure. default nested requirement types can be overriden using an environment variable

I don't have any drivers on my local since I use zalenium grid or bonigarcia webdriver manager to take care of this. I will contribute my `DriverSource`s implementation once I have more time

**Pull request closed without merging**
