### PR TITLE
Gradle plugin class SerenityPlugin is not thread-safe, take2

### PR DESCRIPTION
**Pull request by ariksher-nex**
solves issue #1396

### CODE REVIEW

**Comment by wakaleo** [comment]
Do you have some tests to demonstrate that this works correctly?

**Comment by ariksher-nex** [comment]
> Do you have some tests to demonstrate that this works correctly?

I'm running the `gradlew build` command and there was no problem there.
I assumed there are already tests around it.
the fixed code is on groovy language and apparently the build is not compiling it....
it is not my project and I don't have a full, right way to test it.
sorry.

**Comment by ariksher-nex** [comment]
whats wrong with the build?
I cannot see the output when clicking on **Details**

**Comment by wakaleo** [comment]
Integrated manually in 2.0.7

**Pull request closed without merging**
