### PR TITLE
Fix #2804 - Json file not contains data based on display name generator

### LINKED ISSUE #2804: [Serenity 3.2.4][Junit5]: Json file not containing data based on custom display name generator
JSON file generated under target/site/serenity not containing data based on the Junit 5 custom display name generator. 

Please find the repo to reproduce issue: https://github.com/bachhavdipak/serenityJunit5/blob/main/src/test/java/starter/wikipedia/When_Searching_For_Terms.java

`{"name":"**search_by_single_keyword**","id":"**starter.wikipedia.When_Searching_For_Terms:search_by_single_keyword**","testCaseName":"starter.wikipedia.When_Searching_For_Terms","testSteps":[{"number":1,"description":"Navigate to the home page","duration":11470,"startTime":"2022-04-29T16:13:55.613+01:00[Europe/London]","screenshots":[{"screenshot":"d766ead5fa01902c43be6987673597ff3933826d50b64c72d7bbd153ebd0b126.png","timeStamp":1651245247083,"screenshotName":"d766ead5fa01902c43be6987673597ff3933826d50b64c72d7bbd153ebd0b126.png"}],"result":"SUCCESS","precondition":false,"level":0},{"number":2,"description":"Search by keyword \u0027Everest\u0027","duration":3247,"startTime":"2022-04-29T16:14:07.091+01:00[Europe/London]","screenshots":[{"screenshot":"597b79a182df41a4c47e54e1b2e766985064982352a407925041c61c53d69d28.png","timeStamp":1651245250338,"screenshotName":"597b79a182df41a4c47e54e1b2e766985064982352a407925041c61c53d69d28.png"}],"result":"SUCCESS","precondition":false,"level":0},{"number":3,"description":"The first heading should be \u0027Mount Everest\u0027","duration":1466,"startTime":"2022-04-29T16:14:10.380+01:00[Europe/London]","screenshots":[{"screenshot":"ad257c4fb289f56e4535629912587c88d9ad275b9c90ec2182936e0578cf5941.png","timeStamp":1651245250928,"screenshotName":"ad257c4fb289f56e4535629912587c88d9ad275b9c90ec2182936e0578cf5941.png"}],"result":"SUCCESS","precondition":false,"level":0}],"userStory":{"id":"starter.wikipedia.When_Searching_For_Terms","storyName":"When searching for terms","displayName":"When searching for terms","storyClassName":"starter.wikipedia.When_Searching_For_Terms","path":"wikipedia","type":"story"},"featureTag":{"name":"Wikipedia/When searching for terms","type":"story","displayName":"Wikipedia/When searching for terms"},"title":"Search by single keyword","tags":[{"name":"Wikipedia/When searching for terms","type":"story","displayName":"When searching for terms"},{"name":"Wikipedia","type":"feature","displayName":"Wikipedia"}],"startTime":"2022-04-29T16:13:54.262+01:00[Europe/London]","duration":18408,"projectKey":"","driver":"","isManualTestingUpToDate":false,"manual":false,"testSource":"JUnit5","order":0,"result":"SUCCESS"}
`

image

Code:

```
import Framework.Annotations.Common.MyTest;
import net.serenitybdd.core.Serenity;
import net.serenitybdd.junit5.SerenityJUnit5Extension;
import net.thucydides.core.annotations.Managed;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.WebDriver;

import static org.assertj.core.api.Assertions.assertThat;

@ExtendWith(SerenityJUnit5Extension.class)
@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
class When_Searching_For_Terms {

    /**
     * Define the webdriver instance to be used for these tests
     */
    @Managed(driver = "chrome", options = "")
    WebDriver driver;

    /**
     * Navigation actions. This is a UIInteraction class so it will be instantiated automatically by Serenity.
     */
    NavigateActions navigate;

    /**
     * Actions related to searches. This is a UIInteraction class so it will be instantiated automatically by Serenity.
     */
    SearchActions search;

    /**
     * A page object representing a Wikipedia article that is currently appearing in the browser.
     * Page Objects are automatically initialised by Serenity.
     */
    DisplayedArticle displayedArticle;

    @MyTest
    void search_by_single_keyword() {

        navigate.toTheHomePage();

        search.searchBy("Everest");
        Serenity.reportThat("The first heading should be 'Mount Everest'",
                () -> assertThat(displayedArticle.getFirstHeading()).isEqualTo("Mount Everest")
        );
        driver.close();
    }
```
```
import org.apiguardian.api.API;
import org.junit.jupiter.api.DisplayNameGeneration;
import org.junit.jupiter.api.DisplayNameGenerator;
import org.junit.jupiter.api.Test;
import java.lang.annotation.*;
import static org.apiguardian.api.API.Status.STABLE;

@Target({ ElementType.ANNOTATION_TYPE, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@API(status = STABLE, since = "5.0")
@Inherited
@Test
@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
public @interface MyTest {

}

```

### PR DESCRIPTION
**Pull request by bachhavdipak**
#### Summary of this PR
Json file not contains data based on display name generator
#### Intended effect
@DisplayNameGeneration used to declare a custom display name generator for the annotated test class. Json file generated under target/site/serenity folder dont have data based on DisplayNameGeneration before the pull request. 
#### How should this be manually tested?
You can test changes using https://github.com/bachhavdipak/serenity-core/tree/feature/issues-2804 repo.

image

#### Side effects
No
#### Documentation
NA
#### Relevant tickets
#2804
#2934
#### Screenshots (if appropriate)

**what was before this PR** 
image

and
**How it will be changed”.** 

image

image

### CODE REVIEW

**Comment by bachhavdipak** [comment]
@wakaleo  : Functioanlity again broken and not working as expected with the latest serenity

**Comment by wakaleo** [comment]
Can you propose a fix?

**Comment by bachhavdipak** [comment]
I already raised PR and its merged to main branch but somehow it's again
broken

**Comment by wakaleo** [comment]
The code is still there. Why don't you write a unit test that reproduces what is broken and add it to your change?

**Comment by bachhavdipak** [comment]
Hi @wakaleo :  I am facing issue while compilation. Can you please assist ?
```

[INFO] Changes detected - recompiling the module! :dependency
[INFO] Compiling 6 source files with javac [debug target 11] to target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Digital/serenity-core/serenity-bitbar/src/main/java/net/serenitybdd/plugins/bitbar/BitBarTestSession.java:[3,25] cannot access com.testdroid.api.APIEntity
  bad class file: C:\Users\dipak.bachhav\.m2\repository\com\testdroid\testdroid-api\3.22\testdroid-api-3.22.jar(/com/testdroid/api/APIEntity.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR] /C:/Digital/serenity-core/serenity-bitbar/src/main/java/net/serenitybdd/plugins/bitbar/BitBarTestSession.java:[4,31] cannot access com.testdroid.api.model.APIDeviceSession 
  bad class file: C:\Users\dipak.bachhav\.m2\repository\com\testdroid\testdroid-api\3.22\testdroid-api-3.22.jar(/com/testdroid/api/model/APIDeviceSession.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR] /C:/Digital/serenity-core/serenity-bitbar/src/main/java/net/serenitybdd/plugins/bitbar/BitBarTestSession.java:[79,13] cannot find symbol
  symbol:   class APIDeviceSession
  location: class net.serenitybdd.plugins.bitbar.BitBarTestSession
```

**Comment by wakaleo** [comment]
Looks like an issue with the version of Java you are compiling with?

**Comment by bachhavdipak** [comment]
I have tried with java 11 and openjdk 19. Any specific version do you have?

**Comment by bachhavdipak** [comment]
Hi @wakaleo  :I have successfully resolved the issue and investigated the root cause of Fix #2804. Initially, there was a concern that the JSON file wasn't containing data according to the display name generator. However, upon closer examination, it appears that the JSON generation is functioning as expected, producing the desired output.

Please refer to the screenshot below for clarification:

image


However, when attempting to create JSON files under the target/site/serenity folder, it appears that the generated JSON files do not adhere to the expected naming convention depicted in the screenshot. Instead, they are named based on the method name.

We need to investigate why the expected naming convention isn't being followed and ensure that the JSON files are named according to the specified display name generator.

Please can you assist to resolve thius issue?

**Comment by wakaleo** [comment]
If you are able to propose a PR I would be happy to review - alternatively if you would like to opt for one of the commercial support packages we would be able to prioritise the issues that are important to you.

**Comment by bachhavdipak** [comment]
PR has been raised for you : https://github.com/serenity-bdd/serenity-core/pull/3404

**Pull request merged**
