### PR TITLE
Segregate junit4 dependencies 

### PR DESCRIPTION
**Pull request by nicerloop**
to allow using with cucumber-junit-platform-engine and junit-platform-suite

followup of https://github.com/serenity-bdd/serenity-cucumber6/issues/35 and https://github.com/serenity-bdd/serenity-cucumber5/pull/3

makes https://github.com/nicerloop/serenity-cucumber-starter/tree/use-cucumber-junit-platform-engine-7.0.0 work

### CODE REVIEW

**Comment by wakaleo** [comment]
Thanks, I will merge this in for the next release. Could you write up some documentation about how it works in a short readme file? (I will include it in the new docs).

**Comment by nicerloop** [comment]
see https://github.com/serenity-bdd/serenity-cucumber-starter/pull/61

**Comment by nicerloop** [comment]
Obsoletes https://github.com/serenity-bdd/serenity-cucumber6/pull/36

**Comment by wakaleo** [comment]
> see [serenity-bdd/serenity-cucumber-starter#61](https://github.com/serenity-bdd/serenity-cucumber-starter/pull/61)
> 
> it shows how to use serenity-cucumber, cucumber-junit-platform-engine and junit-platform-suite together

The sample code is good, but for people to be able to use it properly, it needs to be documented. We are putting together an updated version of the Serenity User Guide here: https://github.com/serenity-bdd/serenity-users-guide. Could you have a look at https://github.com/serenity-bdd/serenity-users-guide/tree/main/docs/guide and add a short readme file that explains how to use this feature?

**Comment by nicerloop** [comment]
cucumber-junit uses junit4 and is a dependency of serenity-cucumber.

Should cucumber-junit-platform-engine be the default cucumber integration with serenity described in the documentation, with junit4/cucumber-junit made optional dependencies?

**Comment by wakaleo** [comment]
> I would rather the JUnit 5 integration be the default, though the legacy JUnit 4 integration should continue to work.

**Comment by nicerloop** [comment]
Hi, I looked at https://github.com/serenity-bdd/documentation, and skimmed over https://docusaurus.io/docs.

The thing that annoys me is that much of the contents will be duplicated between the different ways of using Serenity with/without Cucumber with JUnit 4/5 with/without screenplay, such as the pre-requisites, the test scenario, the page objects, generating the reports, etc.

I did not find how to externalize and include common parts of a document, or how to refer to specific sections of another document.

How should I proceed with documenting using serenity with cucumber with junit-platform?

**Comment by wakaleo** [comment]
That's a good point. The docusaurus site will be the target for all the updated docs, and I think the simplest approach is to have tutorials for different tool combinations and then more detailed reference sections which can apply to different approaches. So I would start with a tutorial on "how to write a Serenity BDD test suite with Cucumber and JUnit 5".

**Pull request closed without merging**
