### PR TITLE
Feature/expand property variable references

### PR DESCRIPTION
**Pull request by David-Paterson**
This update introduces automatic expanding of environment variables and system properties references in any serenity.conf and serenity.properties.

Example.
serenity.outputDirectiry=${WORKING_DIRECTORY}/report

### CODE REVIEW

**Comment by David-Paterson** [comment]
Had to correct an integration test.

**Comment by wakaleo** [comment]
Great idea, thanks!

**Comment by wakaleo** [comment]
Had to revert this commit as the unit tests didn't compile. Please take a look and recommit when the tests run successfully.

**Comment by David-Paterson** [comment]
Damn! Will do

**Pull request merged**
