### PR TITLE
Bugfix/issue 1821

### PR DESCRIPTION
**Pull request by sparmboy**

### CODE REVIEW

**Comment by wakaleo** [comment]
This looks like it passes all string values as lists of strings, even if there is only one value: is this intentional/correct?

**Comment by sparmboy** [comment]
When building with v2.0.81 and with the following options set in my properties file:

`
chrome.switches=--disable-extensions,--disable-infobars,--disable-notifications
chrome_preferences.credentials_enable_service=false
chrome_experimental_options.useAutomationExtension=false
chrome_experimental_options.excludeSwitches=enable-automation`

The following error would be thrown:

`
net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (invalid argument: entry 0 of 'firstMatch' is invalid
from invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: cannot parse excludeSwitches
from invalid argument: must be a list
`

The fix ensures that the `excludeSwitches` option is parsed as a list if possible

**Comment by wakaleo** [comment]
But are there other experimental options that need to take a string and not a list? If this is the case, this code would break for those options.

**Comment by sparmboy** [comment]
I dont believe so according to the [chrome driver capabilities page](https://chromedriver.chromium.org/capabilities):

> 

excludeSwitches | list of strings |   | List of Chrome command line switches to exclude that ChromeDriver by default passes when starting Chrome.  Do not prefix switches with --.
-- | -- | -- | --

**Comment by wakaleo** [comment]
debuggerAddress for example is a String, not a list of strings. With this code, it would be passed as a list containing a single string.

**Comment by sparmboy** [comment]
Ah yes. I have updated to add an explicit check for list-based options

**Pull request merged**
