### PR TITLE
Fixes the project Serenity Demo - based on branch master

### PR DESCRIPTION
**Pull request by verhagen**
__WARNING:__ Replaces pull request #140

Several small fixes in all projects, like:

removes unused imports
fixes Java generics issues
Fixes the Serenity Demo project.

### CODE REVIEW

**Comment by wakaleo** [comment]
Hi, unfortunately I can't merge these until the Snap CI builds correctly. It is also quite a lot to review in one go - maybe try to submit several pull requests with fewer commits each time?

**Comment by verhagen** [comment]
@wakaleo can you explain me why the build server can't find the Chrome browser? As seen in the [build log](https://snap-ci.com/serenity-bdd/serenity-core/pull/143/logs/defaultPipeline/6/integration-tests?back_to=build_history) and below here:

__Could not instantiate class org.openqa.selenium.chrome.ChromeDriver__

```
Executing test should_take_screenshots_correctly [net.thucydides.core.webdriver.integration.WhenTakingLargeScreenshots] with result: FAILURE

net.thucydides.core.webdriver.integration.WhenTakingLargeScreenshots > should_take_screenshots_correctly FAILED
    net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
        at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:141)
        at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:128)
        at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:100)
        at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:173)
        at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:168)
        at net.thucydides.core.webdriver.StaticTestSite.open(StaticTestSite.java:60)
        at net.thucydides.core.webdriver.integration.WhenTakingLargeScreenshots.should_take_screenshots_correctly(WhenTakingLargeScreenshots.java:108)

        Caused by:
        net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
            at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:202)
```

The use of Chrome was already hard coded in the class [WhenTakingLargeScreenshots](https://github.com/serenity-bdd/serenity-core/blob/master/serenity-core/src/test/java/net/thucydides/core/webdriver/integration/WhenTakingLargeScreenshots.java#L109)
Line 109:
driver = testSite.open("http:www.google.com", "screenshots/google.html", "chrome");

**Comment by wakaleo** [comment]
I've been investigating this - chrome has updated automatically on Snap-CI
but Snap-CI still has an old version of ChromeDriver.

On 8 October 2015 at 07:45, Tjeerd Verhagen <notifications@github.com>
wrote:

> @wakaleo <https://github.com/wakaleo> can you explain me why the build
> server can't find the Chrome browser? As seen in the build log
> <https://snap-ci.com/serenity-bdd/serenity-core/pull/143/logs/defaultPipeline/6/integration-tests?back_to=build_history>
> and below here:
>
> *Could not instantiate class org.openqa.selenium.chrome.ChromeDriver*
>
> Executing test should_take_screenshots_correctly [net.thucydides.core.webdriver.integration.WhenTakingLargeScreenshots] with result: FAILURE
>
> net.thucydides.core.webdriver.integration.WhenTakingLargeScreenshots > should_take_screenshots_correctly FAILED
>     net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
>         at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:141)
>         at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:128)
>         at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:100)
>         at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:173)
>         at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:168)
>         at net.thucydides.core.webdriver.StaticTestSite.open(StaticTestSite.java:60)
>         at net.thucydides.core.webdriver.integration.WhenTakingLargeScreenshots.should_take_screenshots_correctly(WhenTakingLargeScreenshots.java:108)
>
>         Caused by:
>         net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
>             at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:202)
>
> The use of Chrome was already hard coded in the class
> WhenTakingLargeScreenshots
> <https://github.com/serenity-bdd/serenity-core/blob/master/serenity-core/src/test/java/net/thucydides/core/webdriver/integration/WhenTakingLargeScreenshots.java#L109>
> Line 109:
> driver = testSite.open("http:www.google.com", "screenshots/google.html",
> "chrome");
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/pull/143#issuecomment-146322302>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by verhagen** [comment]
@wakaleo Yesterday evening, I saw already some commits in the _master_ branch, that also let to the same problem. Once Chrome and chromedriver are in synch again, these build failures are probably resolved.

**Comment by wakaleo** [comment]
Yes, I suspect so.

On 8 October 2015 at 18:33, Tjeerd Verhagen <notifications@github.com>
wrote:

> @wakaleo <https://github.com/wakaleo> Yesterday evening, I saw already
> some commits in the *master* branch, that also let to the same problem.
> Once Chrome and chromedriver are in synch again, these build failures are
> probably resolved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/pull/143#issuecomment-146443865>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Pull request merged**
